- README.md
I put this up in Yammer and people are confused by the current instructions on how to get this up and running by themselves.  I hope this might help non webdev folks have an instance up in their home offices.  Took out the stuff about changing the location tag since that seems to be hit or miss on my end, it's very opaque and the average new user will not need it for now.  I'm happy to try and write more documentation for it to flesh out the intended usage.
> Connection details for remoties

- state.json
> Everything is fine

- state.json
add a white background fill to the on fire image
> add white background to onfire

- README.md
- state.json
The goal of this pull request is to enable more people to add content to the in-office flat screen TVs. We do this by making the readme more useful (partially addresses issue #11) and by adding an image with a URL back to the project.
> Self advertise content location

- state.json
Lindsay Kenzig sent us some UX team slides.
here's a link to the doc for content check: https://docs.google.com/a/mozilla.com/presentation/d/1nxgEbfoCRDcqjk9CusBW7_Nh5qiS6fJuDld10mcbM4M
They look alright from a few feet away from my laptop. I haven't checked it on a real TV.
> add ux team slides

- state.json
for our international audience ;)
> MozPDX: Added weather in Celsius

- state.json
Untested, but seems like it should work…
> Add OMFGDOGS.

- state.json
I love this but its super distracting and it stands out so much that it feels like its constantly on the screen.
> Revert "Add OMFGDOGS."

- state.json
> Add Multnomah Falls to PDX great job

- state.json
update state.json - add FFX CampaignMeter static image - working with Chelsea Novak to put up weekly stats of our campaign.
Hi Moz-Corsica maintainers! We have a new graphic for the FFx Campaign currently running! Let me know if you have questions. It's a static image for inclusion into the ambient displays running moz-corsica.
Thanks!
Jonathan
> add FFX CampaignMeter static image

- README.md
The instruction to refresh the page after writing the config was buried a bit too deep
for me to notice. This should make it easier to quickly test corsica or get one running.
Actually, I updated some other bits of the doc while I was at it.
> Make it clear I need to refresh the page

- state.json
```
https://www.flickr.com/photos/134774698@N08/sets/72157655704455571 bg=#000000
```
becomes
> add whistler photo set to ambient rotation

- state.json
The date part of the url got update, so use the new one.
> Readd 'Mozilla is my Dinosaur'

- state.json
This needs to be on the screens in the Toronto office.
> Add Bautista bat flip to Toronto screens

- state.json
per-email request from shannon, removing the WPR metrics slides until they can revise the relative dates to absolute dates
> remove wpr slides

- state.json
Now that Paris has Corsica, we would like a new tag! Merci beaucoup!
> Introduce a new tag: paris

- state.json
Trying to make on of the MOC displays more readable.
> Testing zoom on the MOC screens

- state.json
Added moc1 and moc3 screens to the timer section as these screens only have one webpage displayed that dynamically updates content.
> Added moc1 and moc3 to timer settings

- state.json
Specifically added the number of point releases that happen over the last while.
> Removed a few charts and added some new ones.

- state.json
> Replacing release ADI crash rates with new dashboard

- state.json
senior director, adulte terrible département
> add may 26 speaker series

- state.json
Reverts mozilla/moz-corsica#66
> Revert "10kdays"

- state.json
Link to http://i.imgur.com/Q9b2SDc.jpg which is a public version of our data classification poster.
> Add new data classification poster

- state.json
First stab at reporting metrics. Follow up work will include higher contrast and cleanup for at-a-glance use case.
> Quantum Metrics

- state.json
Initially populate with Mandy's event countdown page.
> Add a tag for ldn (London Office) content

- state.json
fact check my date format, plz
> july speaker series

- state.json
> change speaker slide to september

- state.json
This pull request contains some berlin-specific config
I've added some Berlin weather for starters, but Andreas has access to add further commits, e.g., the new nightly logo just for us to get used to it :)
> Add weather report for berlin office

- state.json
> add YVR weather

- state.json
It's old and unused, but we don't have a better view for now.
Hope to get something better soon.
> Remove bedrock build pipeline

- state.json
From https://www.flickr.com/photos/mozillaallhands/
> Display images from the all hands

- state.json
- Adding gslide for Berlin office events.
- Removing tupperware amnesty. No more amnesty, back to judgemental
stares!
> Update Berlin office slides

- state.json
I think I got all of this right, but I've never used the start and end stuff before, so a second set of eyes would be nice.
> Add family day 2018 to all offices

- state.json
Nobody consistently updated them, i couldn't keep up with it.
> Remove Berlin office events slides

- state.json
> adding to pdx pretty

- state.json
remove batflip image and wifi update image. they are out of date.
> update tor tag

- state.json
added a url for a publicly viewable google slide deck
> update pocket commons with slideshow

- state.json
Global Accessibility Awareness day promo.
> add GAAD promo for 5/15-5/16

- state.json
We're done with this campaign.
> Remove GAAD promo

- state.json
Add Zoom / vidyo transition announcement. Care of AVOps.
> Add Zoom announcement

- state.json
Remove zoom announcement slide.
> remove zoom announcment

- state.json
add items saved chart and SF weather
> add chart and weather to pocket

- state.json
> Add a Rust version slide

- state.json
Made with ❤️  in Toronto w/ @kshvmdn.
> Add Toronto Bike Share

- state.json
Add SFO zoom transition timeline slides to sfo tag.
> update sfo tag in state.json

- state.json
@emceeaich I think we should cycle this out now that the project is done. Please don't merge yet - I'm thinking end of the week would be a good time.
> Remove XBL graph

- state.json
> Add AreWeFluentYet M3 Dashboard

- state.json
updating link for happy tweets
> update nice tweets preso

- state.json
Add the M1 dashboard since we now will focus on driving down M1 to zero.
> Add AWFY Milestone 1 dashboard to rotation.

- state.json
Add a gslide for DUO enrollment instructions for EUS. The QR codes go to our mana page.
> Add DUO Enrollment slide for EUS

- state.json
> Update state.json with new happy tweets for the new year

- state.json
Passed the holiday season so ok to remove pni holiday slide as per Anil Kanji in the Foundation.
> remove pni holiday slide

- state.json
> Update for new happy tweets

- package-lock.json
- package.json
this gets us onto the latest version of corsica, and updates the forever library
> update corsica, forever to latest versions

- package-lock.json
- package.json
the latest version is dependency free
requires landing and publishing this change first:
https://github.com/mythmon/corsica-xkcd/pull/7
> bump corsica-xkcd

- package-lock.json
- package.json
switch to corsica-google-presentation 0.5, which changes a lot of dependencies
> update corsica-google-presentation to the latest 0.5 version

- state.json
the big triage dashboard now returns 403. pullng it from rotation
> bug handling 403s
