.travis.yml
travis deploy was nice, but now that there's built in heroku <-> GH interop we don't need to store this environment specific code in the repo
=> remove travis deploy

state.json
promote the June FF campaign with a static ambient image and an airmo video. also remove the dead postano link in the airmo player
=> add june campaign screencap

state.json
This displays the "crashes / 100 ADI" graph of a random channel (nightly, aurora, beta, release) and product (Firefox desktop or Firefox for Android). Currently this is limited to the recent year of data. Please direct any feedback and suggestions to KaiRo, happy to improve on this!
=> Add office variant of crash graphs

state.json
The display=bigscreen param removes some of the UI items to clean up the interface for the big screen.
=> Added display param to release health dashboards

state.json
Added release health dashboards for all channels to ambient display. Missed this in earlier pull request for platform.
=> Added release health dashboards for all channels

state.json
The releasehealth repo has moved to the Mozilla account on GitHub. Need to update the URLs in Corsica.
=> Update releasehealth dashboard for repo move

state.json
The new Let's Encrypt dashboard graph for Moz (and other interested parties) is at https://letsencrypt.org/stats-dashboard/ .
=> Fixes #71: Update the Let's Encrypt statistics URL

state.json
remove some unused tags, leaves TPE alone in anticipation of adding things in the next week
Did I miss anything? Are these tags actually unused?
=> cleanup :: remove mozfest, brand, servicedesk

state.json
Many of the HTTP URLs also work over HTTPS (or already 301 redirect to the HTTPS URL).
This PR switches all that URLs that were found to work, plus avoids some additional unnecessary redirects for existing HTTPS URLs. A page that 404s has also been removed.
The remaining pages that don't work over HTTPS are:
http://xor.lonnen.com/haneke-2/
http://micropipes.com/temp/
http://whattrainisitnow.com/
http://airmozilla-ops1.corpdmz.scl3.mozilla.com/wowza/
http://cdn.torontolife.com/wp-content/uploads/2015/10/jose-bautista-bat-02-flip.gif
=> Switch to HTTPS content where supported

state.json
Changed the Aurora regression page to show Nightly in response to changes with project Dawn.
=> Change Aurora regression page to Nightly

state.json
I don't know why https://github.com/mozilla/moz-corsica/pull/84 was closed.
Doing a PR in case I convinced you in PR #84
=> Move to whattrainisitnow.com instead of whats-shipping

state.json
Adds https://mozilla.github.io/triage-summary/, code for dashboard at https://github.com/mozilla/triage-summary
=> Add untriaged dashboard to ambients

README.md, state.json
Hi~ I'm Mark, a student worker in Mozilla Taipei Office. I am working in Hasal team, which conducts some speed testing on Firefox and Chrome.
I created some web pages as the dashboard to present our team's testing progress. We would like to combine those pages into your system. Therefore, we can display the content with your project on the TV in our Taipei lab.
=> add tpe-lab tag and content for Hasal team

state.json
releng's release tracking tool now exports a dashboard for corsica, hoping to add it to rotation.
I wasn't sure where to update state.json.
=> adds releng release status dashboard of desktop releases in flight

state.json
Changed sites that were listed as HTTP to HTTPS, to unblock https://github.com/mozilla/dinobuildr/pull/107. Removed two sites that appear to not support HTTPS
=> Convert sites to HTTPS

state.json
Checked with the avops team. They no longer need https://airmozilla-ops1.corpdmz.scl3.mozilla.com/wowza/.
=> Removed decommissioned avops command.

state.json
We are no longer using releasewarrior-data for new release tracking, so we shouldn't use that as a source in corsica for office monitors.
The new place we are using doesn't yet have this data accessible from outside VPN so hold off on adding it in.
=> No longer using releasewarrior to track releases, remove stale data source from corsica

state.json
Filing on behalf of Abbie Woods to remove the lunch slide from the MTV corsica tag (mtv only).
Thanks!
=> Remove lunch slide from MTV tag

state.json
I've shut down the moz-chargers herokuapp and this will remove it from the list. The source is saved and on github if we want to restart it on glitch or some other service
=> removed moz-chargers

.github/workflows/ci.yml, .travis.yml, README.md, script/bootstrap
fixes issue #195 by introducing the configuration necessary to run CI on Github Actions. This also moves to a supported version of node and swaps out 'npm install' for the newly available 'clean install' which is actually what we want in a CI environment.
=> add configuration for github ci

package-lock.json, package.json
I recently updated corsica-flickr-2 plugin to use an actively supported flickr library. As part of that, I factored out the code that touches this library and added a test suite to verify it does what I think it does.
https://github.com/lonnen/corsica-flickr/blob/master/tests.js
The tests don't cover the corsica-coupled setup and they are not part of a CI system because sekrits but I do have these two pieces of supporting documentation:
1. A screenshot of the test suite passing locally
2. An official badge verifying that it "works on my machine"
=> update corsica-flickr-2 to 0.2.2

package-lock.json, package.json
can't figure out where these are used. seems to be copied in from an unmanaged environment
```shell
[22:00:41] $ grep -r --exclude-dir=node_modules --exclude=package-lock.json winston *
package.json:    "winston": "^0.7.3"
```
```shell
[22:01:22] $ grep -r --exclude-dir=node_modules --exclude=package-lock.json forever *
package.json:    "forever": "^3.0.4"
```
=> remove winston, forever

.env
We removed a few plugins from the package listing recently but they're still enumerating in the config and there is a benign error trying to load them at runtime. This cleans that up.
=> remove unimported plugins from the environment

.env, package-lock.json, package.json, state.json
the airmo screens group is empty and the playlist item hasn't worked since the cutover to onlineexperiences. There is a redirect but it loads an empty document. This change removes the playlist, the plugin from the environment, and the package as a dependency
=> remove airmo, rss
